# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{time_crisis}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Travis Tilley"]
  s.date = %q{2009-12-23}
  s.description = %q{date and time related extensions}
  s.email = %q{ttilley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "lib/third_base.rb",
     "lib/third_base/compat.rb",
     "lib/third_base/compat/date.rb",
     "lib/third_base/compat/date/format.rb",
     "lib/third_base/date.rb",
     "lib/third_base/datetime.rb",
     "lib/time_crisis.rb",
     "lib/time_crisis/date_range.rb",
     "lib/time_crisis/ext.rb",
     "lib/time_crisis/holiday.rb",
     "lib/time_crisis/meteorological_seasons.rb",
     "lib/time_crisis/named_months.rb",
     "lib/time_crisis/nth_weekday.rb",
     "lib/time_crisis/support.rb",
     "lib/time_crisis/support/acts_like.rb",
     "lib/time_crisis/support/advance.rb",
     "lib/time_crisis/support/change.rb",
     "lib/time_crisis/support/conversions.rb",
     "lib/time_crisis/support/current.rb",
     "lib/time_crisis/support/readable_inspect.rb",
     "lib/time_crisis/tzinfo.rb",
     "lib/time_crisis/tzinfo/LICENSE",
     "lib/time_crisis/tzinfo/data_timezone.rb",
     "lib/time_crisis/tzinfo/data_timezone_info.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Algiers.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Cairo.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Casablanca.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Harare.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Johannesburg.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Monrovia.rb",
     "lib/time_crisis/tzinfo/definitions/Africa/Nairobi.rb",
     "lib/time_crisis/tzinfo/definitions/America/Argentina/Buenos_Aires.rb",
     "lib/time_crisis/tzinfo/definitions/America/Argentina/San_Juan.rb",
     "lib/time_crisis/tzinfo/definitions/America/Bogota.rb",
     "lib/time_crisis/tzinfo/definitions/America/Caracas.rb",
     "lib/time_crisis/tzinfo/definitions/America/Chicago.rb",
     "lib/time_crisis/tzinfo/definitions/America/Chihuahua.rb",
     "lib/time_crisis/tzinfo/definitions/America/Denver.rb",
     "lib/time_crisis/tzinfo/definitions/America/Godthab.rb",
     "lib/time_crisis/tzinfo/definitions/America/Guatemala.rb",
     "lib/time_crisis/tzinfo/definitions/America/Halifax.rb",
     "lib/time_crisis/tzinfo/definitions/America/Indiana/Indianapolis.rb",
     "lib/time_crisis/tzinfo/definitions/America/Juneau.rb",
     "lib/time_crisis/tzinfo/definitions/America/La_Paz.rb",
     "lib/time_crisis/tzinfo/definitions/America/Lima.rb",
     "lib/time_crisis/tzinfo/definitions/America/Los_Angeles.rb",
     "lib/time_crisis/tzinfo/definitions/America/Mazatlan.rb",
     "lib/time_crisis/tzinfo/definitions/America/Mexico_City.rb",
     "lib/time_crisis/tzinfo/definitions/America/Monterrey.rb",
     "lib/time_crisis/tzinfo/definitions/America/New_York.rb",
     "lib/time_crisis/tzinfo/definitions/America/Phoenix.rb",
     "lib/time_crisis/tzinfo/definitions/America/Regina.rb",
     "lib/time_crisis/tzinfo/definitions/America/Santiago.rb",
     "lib/time_crisis/tzinfo/definitions/America/Sao_Paulo.rb",
     "lib/time_crisis/tzinfo/definitions/America/St_Johns.rb",
     "lib/time_crisis/tzinfo/definitions/America/Tijuana.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Almaty.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Baghdad.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Baku.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Bangkok.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Chongqing.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Colombo.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Dhaka.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Hong_Kong.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Irkutsk.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Jakarta.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Jerusalem.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kabul.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kamchatka.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Karachi.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kathmandu.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kolkata.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Krasnoyarsk.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kuala_Lumpur.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Kuwait.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Magadan.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Muscat.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Novosibirsk.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Rangoon.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Riyadh.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Seoul.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Shanghai.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Singapore.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Taipei.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Tashkent.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Tbilisi.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Tehran.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Tokyo.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Ulaanbaatar.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Urumqi.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Vladivostok.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Yakutsk.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Yekaterinburg.rb",
     "lib/time_crisis/tzinfo/definitions/Asia/Yerevan.rb",
     "lib/time_crisis/tzinfo/definitions/Atlantic/Azores.rb",
     "lib/time_crisis/tzinfo/definitions/Atlantic/Cape_Verde.rb",
     "lib/time_crisis/tzinfo/definitions/Atlantic/South_Georgia.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Adelaide.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Brisbane.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Darwin.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Hobart.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Melbourne.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Perth.rb",
     "lib/time_crisis/tzinfo/definitions/Australia/Sydney.rb",
     "lib/time_crisis/tzinfo/definitions/Etc/UTC.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Amsterdam.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Athens.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Belgrade.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Berlin.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Bratislava.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Brussels.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Bucharest.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Budapest.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Copenhagen.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Dublin.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Helsinki.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Istanbul.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Kiev.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Lisbon.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Ljubljana.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/London.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Madrid.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Minsk.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Moscow.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Paris.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Prague.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Riga.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Rome.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Sarajevo.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Skopje.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Sofia.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Stockholm.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Tallinn.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Vienna.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Vilnius.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Warsaw.rb",
     "lib/time_crisis/tzinfo/definitions/Europe/Zagreb.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Auckland.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Fiji.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Guam.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Honolulu.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Majuro.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Midway.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Noumea.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Pago_Pago.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Port_Moresby.rb",
     "lib/time_crisis/tzinfo/definitions/Pacific/Tongatapu.rb",
     "lib/time_crisis/tzinfo/info_timezone.rb",
     "lib/time_crisis/tzinfo/linked_timezone.rb",
     "lib/time_crisis/tzinfo/linked_timezone_info.rb",
     "lib/time_crisis/tzinfo/offset_rationals.rb",
     "lib/time_crisis/tzinfo/ruby_core_support.rb",
     "lib/time_crisis/tzinfo/time_or_datetime.rb",
     "lib/time_crisis/tzinfo/timezone.rb",
     "lib/time_crisis/tzinfo/timezone_definition.rb",
     "lib/time_crisis/tzinfo/timezone_info.rb",
     "lib/time_crisis/tzinfo/timezone_offset_info.rb",
     "lib/time_crisis/tzinfo/timezone_period.rb",
     "lib/time_crisis/tzinfo/timezone_transition_info.rb",
     "lib/time_crisis/weekend.rb",
     "test/test_helper.rb",
     "test/time_crisis_test.rb",
     "time_crisis.gemspec"
  ]
  s.homepage = %q{http://github.com/ttilley/time_crisis}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{date and time related extensions}
  s.test_files = [
    "test/test_helper.rb",
     "test/time_crisis_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<third_base>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<third_base>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<third_base>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

